export type Faction = "republique" | "csi" | "cartel" | "mandalore" | "neutre";

export type Planet = {
  name: string;
  system: string;
  faction: Faction;
  x: number;
  y: number;
  capital?: boolean;
  blurb: string;
};

export const FACTION_META: Record<Faction, { label: string; color: string }> = {
  republique: { label: "République", color: "var(--republic)" },
  csi: { label: "Confédération des Systèmes Indépendants", color: "var(--separatist)" },
  cartel: { label: "Cartel du Hutt", color: "var(--cartel)" },
  mandalore: { label: "Mandalore / Death Watch", color: "var(--mandalore)" },
  neutre: { label: "Monde neutre", color: "var(--neutral)" },
};

export const WORLD_W = 5460;
export const WORLD_H = 3460;

export const PLANETS: Planet[] = [
  // -- République --
  { name: "Coruscant", system: "Système de Coruscant", faction: "republique", x: 2730, y: 1729, capital: true,
    blurb: "Capitale galactique et siège du Sénat. Cœur battant de la République, ville-planète recouverte d'une seule mégalopole ininterrompue." },
  { name: "Alderaan", system: "Système d’Alderaan", faction: "republique", x: 2583, y: 1601,
    blurb: "Monde pacifiste des Mondes du Noyau, réputé pour ses paysages préservés et son influence diplomatique au Sénat." },
  { name: "Chandrila", system: "Système de Chandrila", faction: "republique", x: 2637, y: 1874,
    blurb: "Berceau historique de la République, ses plaines dorées abritent une longue tradition sénatoriale." },
  { name: "Corellia", system: "Système corellien", faction: "republique", x: 2875, y: 1583,
    blurb: "Grand centre industriel et chantier naval, réputé pour ses pilotes et ses constructeurs de vaisseaux." },
  { name: "Naboo", system: "Système de Naboo", faction: "republique", x: 2510, y: 1911,
    blurb: "Monde natif de la sénatrice Padmé Amidala, allié fidèle de la République depuis l'invasion Trade Federation." },
  { name: "Kamino", system: "Système de Kamino", faction: "republique", x: 2002, y: 2184,
    blurb: "Monde océanique isolé des Régions Inconnues. Ses cloneurs y produisent la Grande Armée de la République." },
  { name: "Kashyyyk", system: "Système de Kashyyyk", faction: "republique", x: 2184, y: 2364,
    blurb: "Monde-forêt des Wookiees, alliés indéfectibles de la République et guerriers redoutés de ses campagnes." },
  { name: "Mon Cala", system: "Système de Dac", faction: "republique", x: 1911, y: 1965,
    blurb: "Monde océanique des Mon Calamari et des Quarren, rallié à la République après une guerre civile sanglante." },
  { name: "Rodia", system: "Système de Rodia", faction: "republique", x: 1729, y: 2184,
    blurb: "Monde jungle des Rodiens, libéré du blocus séparatiste grâce à l'intervention républicaine." },
  { name: "Malastare", system: "Système de Malastare", faction: "republique", x: 2275, y: 2546, capital: true,
    blurb: "Monde riche en carburant fossile, membre influent de la République malgré les tensions Gran/Dug." },
  { name: "Anaxes", system: "Système d’Anaxes", faction: "republique", x: 3003, y: 2093, capital: true,
    blurb: "Immense chantier naval républicain, cible d'une offensive séparatiste majeure en fin de guerre." },
  { name: "Christophsis", system: "Système de Christophsis", faction: "republique", x: 3185, y: 1820,
    blurb: "Monde aux cités de cristal, théâtre de la toute première grande bataille de la guerre." },
  { name: "Saleucami", system: "Système de Saleucami", faction: "republique", x: 2455, y: 2637,
    blurb: "Avant-poste désertique de la République, garnison clone stratégique dans la Bordure Extérieure." },
  { name: "Bothawui", system: "Système de Bothawui", faction: "republique", x: 1638, y: 1729,
    blurb: "Monde des Bothans, relais d'informations et de ravitaillement essentiel pour l'effort de guerre républicain." },
  { name: "Felucia", system: "Système de Felucia", faction: "republique", x: 1911, y: 2455,
    blurb: "Monde fongique aux couleurs éclatantes, garnison républicaine sous le commandement du Général Secura." },
  { name: "Ryloth", system: "Système de Ryloth", faction: "republique", x: 1456, y: 1911,
    blurb: "Monde twi'lek libéré du blocus séparatiste par la République et la résistance de Cham Syndulla." },
  { name: "Pantora", system: "Système de Pantora", faction: "republique", x: 2912, y: 1272,
    blurb: "Monde glacé des Pantorans, dont la représentante siège fidèlement au Sénat Galactique." },
  { name: "Kiros", system: "Système de Kiros", faction: "republique", x: 1820, y: 2730,
    blurb: "Colonie togruta réduite en esclavage par les Zygerriens, libérée par la République et Anakin Skywalker." },
  { name: "Cerea", system: "Système de Cerea", faction: "republique", x: 3094, y: 1547,
    blurb: "Monde montagneux natal du Maître Jedi Ki-Adi-Mundi, fidèle allié de la République." },
  { name: "Glee Anselm", system: "Système de Glee Anselm", faction: "republique", x: 2693, y: 2093,
    blurb: "Monde aquatique des Nautolans, patrie du Maître Jedi Kit Fisto." },
  { name: "Duro", system: "Système de Duro", faction: "republique", x: 3003, y: 1365,
    blurb: "Monde-usine des Duros, l'une des espèces fondatrices de la République galactique." },
  { name: "Kaller", system: "Système de Kaller", faction: "republique", x: 2184, y: 1547,
    blurb: "Avant-poste boisé de la République, garnison clone en première ligne contre les forces séparatistes." },
  { name: "Murkhana", system: "Système de Murkhana", faction: "republique", x: 2546, y: 1365,
    blurb: "Monde urbain lourdement bombardé, disputé âprement entre forces républicaines et séparatistes." },
  { name: "Kadavo", system: "Système de Kadavo", faction: "republique", x: 1911, y: 2821,
    blurb: "Lune-prison des marchands d'esclaves zygerriens, prise d'assaut par la République durant la crise de Kiros." },
  { name: "Ord Mantell", system: "Système d’Ord Mantell", faction: "republique", x: 1547, y: 1911,
    blurb: "Monde sans foi ni loi patrouillé par la République, terrain de chasse favori des chasseurs de primes." },
  { name: "Kuat", system: "Système de Kuat", faction: "republique", x: 2912, y: 1729,
    blurb: "Siège des chantiers Kuat Drive Yards, qui construisent les croiseurs de classe Venator de la République." },
  { name: "Eriadu", system: "Système d’Eriadu", faction: "republique", x: 3367, y: 2093,
    blurb: "Monde industriel de la Bordure Extérieure, patrie du gouverneur Wilhuff Tarkin." },
  { name: "Fondor", system: "Système de Fondor", faction: "republique", x: 2821, y: 1820,
    blurb: "Second grand centre de construction navale républicain, complément stratégique de Kuat." },
  { name: "Rishi", system: "Système de Rishi", faction: "republique", x: 1638, y: 2093,
    blurb: "Lune tropicale abritant un avant-poste clone de surveillance à la frontière de la Bordure Extérieure." },
  { name: "Shili", system: "Système de Shili", faction: "republique", x: 2093, y: 1820,
    blurb: "Monde savane natal des Togruta, patrie de la Padawan Ahsoka Tano." },
  { name: "Subterrel", system: "Système de Subterrel", faction: "republique", x: 1820, y: 2275,
    blurb: "Monde minier proche de Kamino, lié au ravitaillement du programme des clones." },
  { name: "Sullust", system: "Système de Sullust", faction: "republique", x: 1729, y: 1638,
    blurb: "Monde volcanique aux cités souterraines, allié commercial de longue date de la République." },
  { name: "Ossus", system: "Système d’Ossus", faction: "republique", x: 2637, y: 1729,
    blurb: "Ancien monde sacré des Jedi, dépositaire d'archives et d'enseignements millénaires." },
  { name: "Bora Vio", system: "Système de Bora Vio", faction: "republique", x: 2093, y: 2275,
    blurb: "Monde aux nuages denses, hébergeant une installation kaminoenne liée au programme des clones." },
  { name: "Dantooine", system: "Système de Dantooine", faction: "republique", x: 2093, y: 2637,
    blurb: "Monde rural aux vastes prairies, terrain d'une enquête de la Jedi Ahsoka Tano." },
  { name: "Ord Cestus", system: "Système d’Ord Cestus", faction: "republique", x: 2637, y: 1547,
    blurb: "Avant-poste médical républicain, spécialisé dans le soin et l'équipement des soldats clones." },
  { name: "Ilum", system: "Système d’Ilum", faction: "republique", x: 2364, y: 1272,
    blurb: "Monde glacé sacré de l'Ordre Jedi, où les jeunes Padawans récoltent leur premier cristal kyber." },
  { name: "Carida", system: "Système de Carida", faction: "republique", x: 2730, y: 2275,
    blurb: "Monde montagneux abritant la station spatiale Valor, avant-poste militaire de la République." },
  { name: "Yerbana", system: "Système de Yerbana", faction: "republique", x: 3185, y: 2275,
    blurb: "Monde aux vertes plaines, site d'une victoire décisive du Général Skywalker sur les forces séparatistes." },

  // -- C.S.I. --
  { name: "Geonosis", system: "Système de Geonosis", faction: "csi", x: 3822, y: 1001, capital: true,
    blurb: "Monde désertique aux ruches geonosiennes, où furent forgés les premiers plans de la Mort Noire et l'armée droïde." },
  { name: "Mustafar", system: "Système de Mustafar", faction: "csi", x: 4186, y: 728,
    blurb: "Planète volcanique riche en minerais rares, exploitée par des intérêts miniers alignés sur la Confédération." },
  { name: "Utapau", system: "Système d’Utapau", faction: "csi", x: 4004, y: 1181,
    blurb: "Monde neutre aux gigantesques dolines, resté à l'écart du conflit avant d'être investi par la Confédération dans les derniers jours de la guerre." },
  { name: "Raxus", system: "Système de Raxus", faction: "csi", x: 4368, y: 1001,
    blurb: "Ancien monde industriel devenu décharge planétaire, aujourd'hui refuge des chantiers droïdes de la C.S.I." },
  { name: "Cato Neimoidia", system: "Système de Cato Neimoidia", faction: "csi", x: 3549, y: 691,
    blurb: "Cités-ponts suspendues des Neimoidiens, dont la Fédération du Commerce finance largement l'effort séparatiste." },
  { name: "Muunilinst", system: "Système de Muunilinst", faction: "csi", x: 4550, y: 1272, capital: true,
    blurb: "Monde-banque des Muuns, siège du Clan Bancaire InterGalactique qui finance la Confédération." },
  { name: "Serenno", system: "Système de Serenno", faction: "csi", x: 3913, y: 546, capital: true,
    blurb: "Monde aristocratique natal du Comte Dooku, chef politique de la Confédération des Systèmes Indépendants." },
  { name: "Skako Minor", system: "Système de Skako", faction: "csi", x: 4459, y: 546,
    blurb: "Monde du Techno-Syndicat, laboratoires secrets où sont conçues certaines des pires créations de Grievous." },
  { name: "Umbara", system: "Système d’Umbara", faction: "csi", x: 3731, y: 1365,
    blurb: "Monde crépusculaire aux teintes violettes, fournisseur de chasseurs stellaires à la Confédération." },
  { name: "Zygerria", system: "Système de Zygerria", faction: "csi", x: 4277, y: 1547,
    blurb: "Monde des marchands d'esclaves zygerriens, alliés opportunistes de la Confédération pendant la guerre." },
  { name: "Onderon", system: "Système d’Onderon", faction: "csi", x: 3458, y: 1181,
    blurb: "Monde placé sous un régime fantoche pro-séparatiste, avant d'être libéré par une rébellion locale." },
  { name: "Lola Sayu", system: "Système de Lola Sayu", faction: "csi", x: 4641, y: 819,
    blurb: "Astéroïde-forteresse abritant la Citadelle, prison de haute sécurité de la Confédération." },
  { name: "Vassek", system: "Système de Vassek", faction: "csi", x: 4730, y: 1092,
    blurb: "Lune fortifiée servant de repaire au Général Grievous, loin des lignes de front républicaines." },
  { name: "Mygeeto", system: "Système de Mygeeto", faction: "csi", x: 3640, y: 910,
    blurb: "Monde cristallin glacé, place forte du Clan Bancaire disputée jusqu'aux tout derniers jours de la guerre." },
  { name: "Hypori", system: "Système d’Hypori", faction: "csi", x: 4186, y: 1547,
    blurb: "Avant-poste industriel du Techno-Syndicat, théâtre d'une bataille précoce et sanglante de la guerre." },
  { name: "Dathomir", system: "Système de Dathomir", faction: "csi", x: 3549, y: 1547,
    blurb: "Monde des Sœurs de la Nuit, dont la sorcière Mère Talzin fournit au Comte Dooku ses plus redoutables agents." },
  { name: "Iridonia", system: "Système d’Iridonia", faction: "csi", x: 3913, y: 1365,
    blurb: "Monde natal des Zabrak, dont plusieurs guerriers rallient la cause du Comte Dooku." },
  { name: "Jabiim", system: "Système de Jabiim", faction: "csi", x: 4550, y: 1547,
    blurb: "Monde boueux déchiré par une guerre civile brutale entre factions loyalistes et séparatistes." },
  { name: "Raydonia", system: "Système de Raydonia", faction: "csi", x: 4730, y: 1365,
    blurb: "Monde jungle dont la population fut massacrée par la Confédération pour attirer un piège à Obi-Wan Kenobi." },
  { name: "Scipio", system: "Système de Scipio", faction: "csi", x: 4459, y: 1729,
    blurb: "Monde enneigé du Clan Bancaire InterGalactique, membre fondateur et financier de la Confédération." },
  { name: "Mahranee", system: "Système de Mahranee", faction: "csi", x: 4821, y: 1729,
    blurb: "Monde attaqué par les forces séparatistes, tragédie apprise alors que Quinlan Vos traquait le Comte Dooku." },

  // -- Mandalore / Death Watch --
  { name: "Mandalore", system: "Système de Mandalore", faction: "mandalore", x: 650, y: 550, capital: true,
    blurb: "Monde-capitale neutre sous la Duchesse Satine, avant d'être renversé par le coup d'État de Death Watch et Maul." },
  { name: "Concord Dawn", system: "Système de Concord Dawn", faction: "mandalore", x: 450, y: 400,
    blurb: "Bastion traditionnel de Death Watch, faction mandalorienne extrémiste opposée au pacifisme de Sundari." },
  { name: "Carlac", system: "Système de Carlac", faction: "mandalore", x: 850, y: 350,
    blurb: "Monde glacé abritant un camp d'entraînement secret de Death Watch, découvert par Ahsoka Tano." },
  { name: "Zanbar", system: "Système de Zanbar", faction: "mandalore", x: 800, y: 750,
    blurb: "Lune isolée servant de camp d'entraînement aux jeunes recrues de Death Watch." },

  // -- Mondes neutres --
  { name: "Toydaria", system: "Système de Toydaria", faction: "neutre", x: 3094, y: 2364,
    blurb: "Monde marécageux dont le roi Katuunko maintient une stricte neutralité, malgré ses sympathies républicaines." },
  { name: "Bespin", system: "Système de Bespin", faction: "neutre", x: 3640, y: 2002,
    blurb: "Cité-nuage minière indépendante, prospérant grâce au commerce du gaz tibanna loin des deux camps." },
  { name: "Iego", system: "Système d’Iego", faction: "neutre", x: 4912, y: 1820,
    blurb: "Monde mystérieux des Régions Inconnues, entouré de légendes et resté hors de portée du conflit." },
  { name: "Bardotta", system: "Système de Bardotta", faction: "neutre", x: 1092, y: 1638,
    blurb: "Monde mystique des Force Priestesses, farouchement isolationniste et étranger aux affaires galactiques." },
  { name: "Aleen", system: "Système d’Aleen", faction: "neutre", x: 910, y: 2002,
    blurb: "Monde souterrain dont les habitants, les Aleena, cultivent une neutralité prudente envers la guerre." },
  { name: "Rugosa", system: "Système de Rugosa", faction: "neutre", x: 2730, y: 910,
    blurb: "Lune isolée ayant accueilli les tout premiers pourparlers secrets entre République et Toydaria." },
  { name: "Abafar", system: "Système d’Abafar", faction: "neutre", x: 3822, y: 2184,
    blurb: "Monde désertique reculé, simple étape sur les routes commerciales de la Bordure Extérieure." },
  { name: "Devaron", system: "Système de Devaron", faction: "neutre", x: 1365, y: 1456,
    blurb: "Monde forestier abritant un ancien temple Jedi, fréquenté par les chasseurs de primes en maraude." },
  { name: "Maridun", system: "Système de Maridun", faction: "neutre", x: 2455, y: 2275,
    blurb: "Monde de prairies abritant la colonie pacifiste des Lurmen, qui refusent de prendre parti dans la guerre." },
  { name: "Mortis", system: "Système de Mortis", faction: "neutre", x: 2912, y: 1092,
    blurb: "Royaume mystique hors du temps, demeure du Père et de ses enfants incarnant la lumière et l'ombre de la Force." },
  { name: "Ruusan", system: "Système de Ruusan", faction: "neutre", x: 1547, y: 1272,
    blurb: "Monde cicatrisé par une antique bataille Jedi-Sith, dont l'écho résonne encore à travers la Force." },
  { name: "Orto Plutonia", system: "Système d’Orto Plutonia", faction: "neutre", x: 2821, y: 1181,
    blurb: "Monde glacé des Talz, farouchement isolationnistes envers les deux camps de la guerre." },
  { name: "Vanqor", system: "Système de Vanqor", faction: "neutre", x: 4004, y: 1820,
    blurb: "Monde reculé, site d'un accident de vaisseau qui mena Kenobi et Skywalker sur la piste du Comte Dooku." },
  { name: "Patitite Pattuna", system: "Système de Patitite Pattuna", faction: "neutre", x: 1272, y: 1365,
    blurb: "Petit monde violet libéré d'un dictateur local grâce à l'intervention inattendue de C-3PO." },
  { name: "Lotho Minor", system: "Système de Lotho Minor", faction: "neutre", x: 4277, y: 1820,
    blurb: "Planète-décharge de la galaxie, où le Seigneur Sith déchu Maul survécut des années durant." },
  { name: "Cybloc", system: "Système de Cybloc", faction: "neutre", x: 4550, y: 1911,
    blurb: "Avant-poste isolé de la Bordure Extérieure, attaqué par Maul et Savage Opress." },
  { name: "Dagobah", system: "Système de Dagobah", faction: "neutre", x: 2275, y: 2912,
    blurb: "Monde marécageux imprégné par la Force, visité par Yoda en quête d'anciens secrets Jedi." },
  { name: "Moraband", system: "Système de Moraband", faction: "neutre", x: 3458, y: 1729,
    blurb: "Ancien monde Sith connu jadis sous le nom de Korriban, gardien de secrets oubliés de la Force." },

  // -- Cartel du Hutt --
  { name: "Tatooine", system: "Système de Tatooine", faction: "cartel", x: 1272, y: 2730, capital: true,
    blurb: "Monde désertique aux confins de la Bordure Extérieure, terrain de chasse des Hutts et repaire de contrebandiers." },
  { name: "Nal Hutta", system: "Système de Y’Toub", faction: "cartel", x: 1001, y: 3003, capital: true,
    blurb: "Capitale marécageuse de l'Espace Hutt, siège du pouvoir des clans criminels qui dominent la région." },
  { name: "Nar Shaddaa", system: "Système de Y’Toub", faction: "cartel", x: 819, y: 2730,
    blurb: "« Lune des Contrebandiers » tentaculaire, plaque tournante du marché noir galactique." },
  { name: "Kessel", system: "Système de Kessel", faction: "cartel", x: 1181, y: 3185,
    blurb: "Monde-prison aux mines de glitterstone, dont le trafic d'épice alimente depuis toujours les réseaux criminels du Cartel." },
  { name: "Teth", system: "Système de Teth", faction: "cartel", x: 1547, y: 3003,
    blurb: "Monde isolé abritant un ancien monastère, théâtre d'intrigues autour de la progéniture de Jabba le Hutt." },
  { name: "Florrum", system: "Système de Florrum", faction: "cartel", x: 635, y: 2455,
    blurb: "Repaire volcanique du pirate Hondo Ohnaka, toléré par les routes commerciales que contrôlent les Hutts." },
  { name: "Oba Diah", system: "Système d’Oba Diah", faction: "cartel", x: 455, y: 2730,
    blurb: "Forteresse du Syndicat Pyke, puissant réseau criminel du trafic d'épice allié au Cartel." },
  { name: "Trandosha", system: "Système de Trandosha", faction: "cartel", x: 546, y: 3003,
    blurb: "Monde natal des chasseurs Trandoshans, souvent au service des Hutts pour traquer esclaves fugitifs et proies." },
  { name: "Wasskah", system: "Système de Wasskah", faction: "cartel", x: 364, y: 3185,
    blurb: "Lune-jungle où les chasseurs Trandoshans traquent pour le sport esclaves et prisonniers évadés." },
];

export const ZONE_POLYGONS: Record<string, string> = {
  republique:
    "M2145,988 L2964,1027 L3445,1495 L3510,2145 L3315,2600 L2795,2964 L2275,3055 L2015,2964 L1950,2535 L1365,2145 L1365,1560 Z",
  csi:
    "M3367,1092 L3549,635 L3913,400 L4368,364 L4730,509 L4912,819 L4876,1181 L4730,1456 L4459,1638 L4095,1601 L3731,1492 L3458,1365 Z",
  cartel:
    "M780,2314 L1300,2405 L1716,2795 L1690,3250 L1365,3445 L975,3484 L585,3380 L325,3185 L234,2860 L260,2535 Z",
  mandalore:
    "M350,250 L700,180 L950,320 L1000,600 L850,850 L600,900 L350,750 L230,480 Z",
};
